// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package questdb

import (
	"database/sql"

	"github.com/google/uuid"
)

type Measurement struct {
	SensorID    uuid.UUID
	Value       float64
	Temperature sql.NullFloat64
	Humidity    sql.NullInt32
	Ts          sql.NullTime
	Metadata    sql.NullString
}

type Sensor struct {
	ID        uuid.UUID
	Name      string
	Location  sql.NullString
	CreatedAt sql.NullTime
}
