// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package questdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMeasurement = `-- name: CreateMeasurement :exec
INSERT INTO measurements (
  sensor_id, value, temperature, humidity, ts, metadata
) VALUES (
  $1, $2, $3, $4, $5, $6
)
`

type CreateMeasurementParams struct {
	SensorID    uuid.UUID
	Value       float64
	Temperature sql.NullFloat64
	Humidity    sql.NullInt32
	Ts          sql.NullTime
	Metadata    sql.NullString
}

func (q *Queries) CreateMeasurement(ctx context.Context, arg CreateMeasurementParams) error {
	_, err := q.db.ExecContext(ctx, createMeasurement,
		arg.SensorID,
		arg.Value,
		arg.Temperature,
		arg.Humidity,
		arg.Ts,
		arg.Metadata,
	)
	return err
}

const createSensor = `-- name: CreateSensor :one
INSERT INTO sensors (
  id, name, location, created_at
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, location, created_at
`

type CreateSensorParams struct {
	ID        uuid.UUID
	Name      string
	Location  sql.NullString
	CreatedAt sql.NullTime
}

func (q *Queries) CreateSensor(ctx context.Context, arg CreateSensorParams) (Sensor, error) {
	row := q.db.QueryRowContext(ctx, createSensor,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.CreatedAt,
	)
	var i Sensor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getMeasurements = `-- name: GetMeasurements :many
SELECT sensor_id, value, temperature, humidity, ts, metadata
FROM measurements
WHERE sensor_id = $1
ORDER BY ts DESC
LIMIT 100
`

func (q *Queries) GetMeasurements(ctx context.Context, sensorID uuid.UUID) ([]Measurement, error) {
	rows, err := q.db.QueryContext(ctx, getMeasurements, sensorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measurement
	for rows.Next() {
		var i Measurement
		if err := rows.Scan(
			&i.SensorID,
			&i.Value,
			&i.Temperature,
			&i.Humidity,
			&i.Ts,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSensor = `-- name: GetSensor :one
SELECT id, name, location, created_at FROM sensors
WHERE id = $1
`

func (q *Queries) GetSensor(ctx context.Context, id uuid.UUID) (Sensor, error) {
	row := q.db.QueryRowContext(ctx, getSensor, id)
	var i Sensor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const listSensors = `-- name: ListSensors :many
SELECT id, name, location, created_at FROM sensors
ORDER BY name
`

func (q *Queries) ListSensors(ctx context.Context) ([]Sensor, error) {
	rows, err := q.db.QueryContext(ctx, listSensors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sensor
	for rows.Next() {
		var i Sensor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
